<?php

/**
 * Implements hook_help().
 */
 function unical_styles_help($path, $arg) {
  switch ($path) {
    case 'admin/help#unical_styles':

      $filepath = dirname(__FILE__) . '/README.md';
      if (file_exists($filepath)) {
        $readme = file_get_contents($filepath);
      }
      else {
        $filepath = dirname(__FILE__) . '/README.txt';
        if (file_exists($filepath)) {
          $readme = file_get_contents($filepath);
        }
      }
      if (!isset($readme)) {
        return NULL;
      }
      if (module_exists('markdown')) {
        $filters = module_invoke('markdown', 'filter_info');
        $info = $filters['filter_markdown'];

        if (function_exists($info['process callback'])) {
          $output = $info['process callback']($readme, NULL);
        }
        else {
          $output = '<pre>' . $readme . '</pre>';
        }
      }
      else {
        $output = '<pre>' . $readme . '</pre>';
      }

      return $output;
  }
}

 /**
 * Implements hook_preprocess_page().
 *
 * Adds our CSS.
 */
function unical_styles_preprocess_page(&$variables) {
   $module_path = drupal_get_path('module', 'unical_styles');
   drupal_add_css($module_path . '/assets/css/styles-calendar.css');
}
